export const metadata = {
  title: 'My First App',
  description: 'Generated by Next.js',
  // favicon: "https://cdn4.iconfinder.com/data/icons/logos-brands-7/512/google_logo-google_icongoogle-512.png"
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex flex-col items-center justify-center w-full min-h-[100dvh]">
        <div className="max-w-[50%] bg-red-600">
        {children}

        </div>
        </body>
    </html>
  )
}
